services:
  # Il Message Broker (Mosquitto) serve per la comunicazione MQTT
  message-broker:
    image: eclipse-mosquitto:latest
    container_name: message-broker
    ports:
      - "1883:1883"
      - "9001:9001"

  # La tua Dashboard Node-RED
  # La tua Dashboard Node-RED
  node-red:
    build: ./node_red_data     
    container_name: node-red
    ports:
      - "1880:1880"
    depends_on:
      - message-broker
    volumes:
      - ./node_red_data:/data
  
  #*****************************************************************************************
  # --- AGGIUNTO DA Davide 12/03/2026: Il Database ---
  #****************************************************************************************

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "davide"
      DOCKER_INFLUXDB_INIT_PASSWORD: "Progetto1234"
      DOCKER_INFLUXDB_INIT_ORG: "SmartGarden"
      DOCKER_INFLUXDB_INIT_BUCKET: "telemetry_data"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "dOzXCt01RpXm58Zh_Twn57mRkeRttHvtmbJi6FdPdM0kJh4D-7t2ldF2Ni8YeUg8QCXCqShqC6xMn8IViISstA=="
    restart: always


  # Il servizio che si occupa di adattare i dati meteo
  weather-service-adaptor:
    build: ./weather_service_adaptor
    container_name: weather-service-adaptor
    environment:
      - TOMORROW_API_KEY=vl2kNb5ZvcIWSMqS7oGfKgOzLTOd7FXf
      - CITY_NAME=Turin
    ports:
      - "8085:8085"
    depends_on:
      - service-catalog
  
  smart-irrigation-service:
    build: ./SmartIrrigationService
    container_name: smart-irrigation-service
    environment:
      - PYTHONUNBUFFERED=1  # <--- AGGIUNGI QUESTA RIGA
    depends_on:
      - message-broker
      - service-catalog
      - weather-service-adaptor
    restart: always

  service-catalog:
    build: ./service_catalog
    container_name: service-catalog
    ports:
      - "8080:8080"
    volumes:
      - ./service_catalog/catalogManager.json:/app/catalogManager.json
    restart: always
  

  #*****************************************************************************************
  # --- AGGIUNTO DA Davide 26/03/2026: L'InfluxDB Adaptor ---
  #****************************************************************************************
  influx-adaptor:
    build: ./influx_adaptor
    container_name: influx-adaptor
    ports:
      - "8081:8081"
    depends_on:
      - message-broker
      - service-catalog
      - influxdb
    restart: always


  statistics-service:
    build: ./statistics-service
    container_name: statistics-service
    ports:
      - "8082:8082"
    environment:
      # Natalia (InfluxDB Adaptor) è raggiungibile a porta 8081
      - INFLUX_ADAPTOR_URL=http://influx-adaptor:8081
    depends_on:
      - influx-adaptor
      - influxdb
    restart: always