version: '3.8'

services:
  # Il Message Broker (Mosquitto) serve per la comunicazione MQTT
  message-broker:
    image: eclipse-mosquitto:latest
    container_name: message-broker
    ports:
      - "1883:1883"
      - "9001:9001"

  # La tua Dashboard Node-RED
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    depends_on:
      - message-broker
    volumes:
      - ./node_red_data:/data
  
  #*****************************************************************************************
  # --- AGGIUNTO DA Davide 12/03/2026: Il Database ---
  #****************************************************************************************

  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      # Configurazione automatica! Non dovrai farla dal browser
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=davide
      - DOCKER_INFLUXDB_INIT_PASSWORD=Progetto1234
      - DOCKER_INFLUXDB_INIT_ORG=SmartGarden
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dOzXCt01RpXm58Zh_Twn57mRkeRttHvtmbJi6FdPdM0kJh4D-7t2ldF2Ni8YeUg8QCXCqShqC6xMn8IViISstA==


  # Il servizio che si occupa di adattare i dati meteo
  weather-service-adaptor:
    build: ./weather_service_adaptor
    container_name: weather-service-adaptor
    environment:
      - TOMORROW_API_KEY=vl2kNb5ZvcIWSMqS7oGfKgOzLTOd7FXf
      - CITY_NAME=Turin
    ports:
      - "8085:8085"
    depends_on:
      - service-catalog
  
  smart-irrigation-service:
    build: ./SmartIrrigationService
    container_name: smart-irrigation-service
    environment:
      - PYTHONUNBUFFERED=1  # <--- AGGIUNGI QUESTA RIGA
    depends_on:
      - message-broker
      - service-catalog
      - weather-service-adaptor
    restart: always

  service-catalog:
    build: ./service_catalog
    container_name: service-catalog
    ports:
      - "8080:8080"
    volumes:
      - ./service_catalog/catalogManager.json:/app/catalogManager.json
    restart: always


  # 3. IL TUO DEVICE CONNECTOR
  device_connector:
    build: ./device_connector
    container_name: rpi_connector
    environment:
      # L'URL esatto che il tuo script userà per le chiamate REST
      - CATALOG_BASE_URL=http://service-catalog:8080 
      - DEVICE_ID=RPi_001
    depends_on:
      - message-broker
      - service-catalog

  # 4. IL TUO TELEGRAM BOT
  telegram_bot:
    build: ./Telegram_Bot
    container_name: telegram_bot
    env_file:
      - ./Telegram_Bot/.env  # Il tuo file segreto con il token
    environment:
      - BROKER_IP=message-broker
      # L'endpoint corretto per il PUT della coltura
      - SLOTS_URL=http://service-catalog:8080/slots 
    depends_on:
      - message-broker
      - service-catalog