version: '3.8'

services:
  # Il Message Broker (Mosquitto) serve per la comunicazione MQTT
  message-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"

  # La tua Dashboard Node-RED
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    depends_on:
      - message-broker