FROM python:3.9-slim
WORKDIR /app

# Installiamo tutte le librerie necessarie direttamente:
RUN pip install --no-cache-dir pyTelegramBotAPI paho-mqtt requests python-dotenv

# Usiamo il nome esatto del tuo file con le maiuscole
COPY telegram_bot.py .
CMD ["python", "telegram_bot.py"]