import re

with open("Telegram_Bot/Telegram_Bot.py", "r", encoding="utf-8") as f:
    code = f.read()

# Variable names and functions (use word boundary to avoid partial replacements)
var_replacements = {
    "benvenuto": "welcome_message",
    "comando": "command",
    "testo": "message_text",
    "azione": "action_str",
    "griglia_str": "grid_str",
    "riga": "row_str",
    "coordinata": "coordinate",
    "nuova_posizione": "new_location",
    "legenda": "legend",
    "slot_occupati": "occupied_slots",
    "btn_coltura": "btn_crop",
    "btn_dispositivi": "btn_devices",
    "btn_prezzo": "btn_price",
    "btn_soglie": "btn_thresholds",
    "btn_status": "btn_status",
    "btn_admin": "btn_admin",
    "btn_posizione": "btn_location",
    "btn_profilo": "btn_profile",
    "btn_pos": "btn_pos",
    "btn_si": "btn_yes",
    "btn_no": "btn_no",
    "trovato": "found",
    "filone": "row_pump",
    "rubinetto": "tap",
    "coltura": "crop",
    "dispositivi": "devices",
    "prezzo": "price",
    "soglie": "thresholds",
    "profilo": "profile",
    "posizione": "location",
    "giardino": "garden",
    "dimensioni": "dimensions",
    "handle_coltura": "handle_crop",
    "handle_dispositivi": "handle_devices",
    "handle_prezzo": "handle_price",
    "handle_soglie": "handle_thresholds",
    "handle_profilo": "handle_profile",
    "handle_menu_posizione": "handle_menu_location",
    "handle_citta": "handle_city",
    "process_citta": "process_city",
    "handle_status": "handle_status",
    "handle_admin_panel": "handle_admin_panel",
    "handle_add_slot": "handle_add_slot",
    "handle_remove_slot": "handle_remove_slot",
    "handle_add_device": "handle_add_device",
    "handle_remove_device": "handle_remove_device",
    "handle_add_plant": "handle_add_plant",
    "handle_remove_plant": "handle_remove_plant",
    "handle_add_user": "handle_add_user",
    "handle_remove_user": "handle_remove_user",
    "handle_set_dimensions": "handle_set_dimensions",
    "process_set_dimensions": "process_set_dimensions",
    "handle_dim_callback": "handle_dim_callback",
    "handle_show_garden": "handle_show_garden",
    "genera_griglia_testo": "generate_text_grid",
    "testo_conflitti": "conflict_text",
    "nuovo_prezzo": "new_price",
    "nuova_soglia": "new_threshold",
    "nuovo_valore": "new_value",
    "nome_pianta": "crop_name",
    "soglia_umidita": "moisture_threshold",
    "parti": "parts"
}

for it, en in var_replacements.items():
    code = re.sub(r'\b' + it + r'\b', en, code)

# Comments and remaining strings
str_replacements = {
    "# Aggiungi questa libreria": "# Add this library",
    "# Questa funzione cerca un file chiamato \".env\" nella cartella corrente e lo carica": "# This function looks for a file named \".env\" in the current folder and loads it",
    "# 1. Ottieni questo token scrivendo a @BotFather su Telegram": "# 1. Get this token by writing to @BotFather on Telegram",
    "# Variabile per salvare l'ID della chat dell'utente (per potergli inviare i messaggi MQTT)": "# Variable to save the user's chat ID (to send MQTT messages)",
    "# --- CALLBACK MQTT (Gestione Notifiche in Ingresso) ---": "# --- MQTT CALLBACK (Incoming Notifications Management) ---",
    "# Il bot si iscrive ai topic degli allarmi e della pompa": "# The bot subscribes to alarms and pump topics",
    "# 1. Decodifica e formattazione del messaggio": "# 1. Message decoding and formatting",
    "# Decodifichiamo il SenML (es. [{\"v\": 1, ...}])": "# Decode SenML (e.g. [{\"v\": 1, ...}])",
    "# Prende il valore 1 o 0": "# Gets the value 1 or 0",
    "# Spacchettiamo il JSON per evitare i problemi di formattazione": "# Unpack the JSON to avoid formatting issues",
    "# 2. Invio a tutti gli utenti registrati": "# 2. Send to all registered users",
    "# --- HANDLER TELEGRAM (Gestione Interazione User) ---": "# --- TELEGRAM HANDLER (User Interaction Management) ---",
    "# --- MENU PRINCIPALE (DASHBOARD) ---": "# --- MAIN MENU (DASHBOARD) ---",
    "# Salviamo l'ID per le notifiche MQTT": "# Save ID for MQTT notifications",
    "# Creiamo la pulsantiera professionale": "# Create the professional keyboard",
    "# Riga 1: Gestione principale": "# Row 1: Main management",
    "# Riga 2: Dati e Impostazioni": "# Row 2: Data and Settings",
    "# Riga 3: Live Status": "# Row 3: Live Status",
    "# Riga 4: Admin e Posizione": "# Row 4: Admin and Location",
    "# Riga 4: Profilo utente (centrato, prende tutta la larghezza)": "# Row 4: User Profile (centered, takes full width)",
    "# --- ROUTER DEL MENU ---": "# --- MENU ROUTER ---",
    "# Questa funzione \"ascolta\" i click sui bottoni del menu e richiama le funzioni che abbiamo già creato!": "# This function \"listens\" to button clicks and calls the functions",
    "# Rimuove il \"caricamento\" sul bottone": "# Remove \"loading\" on button",
    "# In base al bottone cliccato, deviamo il traffico alla funzione corretta": "# Depending on the clicked button, route traffic to the correct function",
    "# passando 'call.message' in modo che la funzione risponda nella chat giusta": "# passing 'call.message' so the function responds in the correct chat",
    "# Riga 1: Slot": "# Row 1: Slot",
    "# Riga 2: Device": "# Row 2: Device",
    "# Riga 3: Piante": "# Row 3: Crops",
    "# Riga 4: Utenti": "# Row 4: Users",
    "# Riga 5: Dimensioni e Giardino": "# Row 5: Dimensions and Garden",
    "# 1. Chiediamo al catalogo la lista AGGIORNATA degli slot": "# 1. Get the UPDATED list of slots from the catalog",
    "# 2. Creiamo un bottone dinamicamente per ogni slot trovato nel file JSON": "# 2. Dynamically create a button for each slot found in the JSON file",
    "# Crea il bottone e aggiungilo alla tastiera": "# Create the button and add it to the keyboard",
    "# Chiediamo al catalogo le strategie (per sapere le soglie attuali)": "# Get strategies from catalog (to know current thresholds)",
    "# Usa il nome custom dello slot, oppure Slot_ID se non lo trova": "# Use custom slot name, or Slot_ID if not found",
    "# Mostriamo la strategia attuale": "# Show current strategy",
    "# Registriamo il prossimo passo": "# Register next step",
    "# prepariamo il nuovo JSON da inviare al catalogo (PATCH o PUT a seconda dell'API)": "# Prepare new JSON to send to catalog",
    "# Modifichiamo l'umidità solo se è valida": "# Modify moisture only if valid",
    "# 1. Chiediamo i device al catalogo": "# 1. Get devices from catalog",
    "# Mostra solo i device attivi": "# Show only active devices",
    "# Se ci sono device attivi": "# If there are active devices",
    "# Prepariamo il payload per la PUT degli utenti": "# Prepare payload for users PUT",
    "# Inizializziamo il telegramChatID vuoto. L'utente lo riempirà poi usando /profilo": "# Initialize empty telegramChatID. User will fill it later via /profile",
    "# OPZIONE A: Posizione Testuale": "# OPTION A: Text Location",
    "# OPZIONE B: Posizione GPS con il tasto speciale di Telegram": "# OPTION B: GPS Location with special Telegram button",
    "# Creiamo una tastiera \"Reply\" (quelle in basso) con un bottone speciale nativo di Telegram": "# Create a Reply Keyboard (bottom bar) with native Telegram button",
    "# Questo handler scatta in automatico quando l'utente preme il bottone GPS": "# This handler triggers automatically when the user presses the GPS button",
    "# Rimuoviamo la tastiera speciale e diamo conferma": "# Remove special keyboard and confirm",
    "# --- GESTIONE VISIVA DEL GIARDINO (GRIGLIA) ---": "# --- VISUAL GARDEN MANAGEMENT (GRID) ---",
    "\"\"\"Genera la griglia visiva usando le Emoji di Telegram\"\"\"": "\"\"\"Generates the visual grid using Telegram Emojis\"\"\"",
    "# Costruiamo l'intestazione superiore (R1, R2, ecc.)": "# Build the top header (R1, R2, etc.)",
    "# Spazio iniziale per allineare": "# Initial space to align",
    "# Disegniamo la terra e le piante": "# Draw dirt and plants",
    "# Mettiamo P1, P2 in grassetto": "# Put P1, P2 in bold",
    "# Piantina (Occupato)": "# Crop (Occupied)",
    "# Terra (Libero)": "# Dirt (Empty)",
    "# Aggiungiamo una piccola legenda in fondo": "# Add a small legend at the bottom",
    "# NOTA: Niente più backtick (```), inviamo direttamente il testo formattato!": "# NOTE: No more backticks (```), we send formatted text directly!",
    "# COMANDO: IMPOSTA DIMENSIONI GIARDINO": "# COMMAND: SET GARDEN DIMENSIONS",
    "# Recupera tutti gli slot correnti per verificare i conflitti": "# Fetch all current slots to check for conflicts",
    "# slot_id è tipo P1_R2.": "# slot_id is like P1_R2.",
    "# Ci sono conflitti": "# There are conflicts",
    "# Salviamo le nuove dimensioni nella callback data. (Max 64 bytes per callback_data)": "# Save new dimensions in callback data (Max 64 bytes)",
    "# Se non ci sono conflitti, aggiorna subito": "# If no conflicts, update immediately",
    "# 1. Recupera gli slot ed elimina quelli fuori range": "# 1. Fetch slots and delete those out of range",
    "# 2. Aggiorna la grid": "# 2. Update grid",
    "# COMANDO: VISUALIZZA GIARDINO": "# COMMAND: SHOW GARDEN",
    "# 1. Setup MQTT in background": "# 1. Setup MQTT in background",
    "# Avvia MQTT in un thread separato": "# Start MQTT in a separate thread",
    "# 2. Avvio Bot Telegram in primo piano": "# 2. Start Telegram Bot in foreground"
}

for it, en in str_replacements.items():
    code = code.replace(it, en)

with open("Telegram_Bot/Telegram_Bot.py", "w", encoding="utf-8") as f:
    f.write(code)
