FROM python:3.9-slim
WORKDIR /app

# Niente COPY requirements.txt! Installiamo le due librerie direttamente:
RUN pip install --no-cache-dir paho-mqtt==1.6.1 requests

COPY device_connector.py .
CMD ["python", "device_connector.py"]